# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BSAppium

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:


jobs:
  Sauce-Labs-App-Automate:
    runs-on: windows-latest
    name: Appium Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install requirements 
        run: |
          pip3 install -r requirements.txt
      - name: run Appium script
        run: |
          cd Appium
          python BSAppium.py
    
