# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Online try

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:


jobs:
  Sauce-Labs-App-Automate:
    runs-on: ubuntu-latest
    name: Appium Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Run Appium Server
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
      - name: run behave file
        run: |
          cd Appium
          python Appium.py
    
